### ISSUE TITLE
uninitialized constant Win32::Screenshot::Take (NameError)

### ISSUE THREAD

**Issue by s101070791** [jarmo/win32screenshot#23] opened 2016-06-08 08:49 UTC
require 'win32/screenshot'
Win32::Screenshot::Take.of(:foreground).write("image.png")

**Comment by jarmo** [comment] 2016-06-09 06:52
What version of _win32screenshot_ are you using? What version of Ruby are you using? What version of Windows are you using?

Please include full backtrace as well.

**Comment by s101070791** [comment] 2016-06-12 02:22
win7 x64 + ruby2.2.4 + win32screenshot (2.1.0)

**Comment by s101070791** [comment] 2016-06-12 02:26
C:\Users\Administrator>ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]

C:\Users\Administrator>gem list win

*** LOCAL GEMS ***

rdp-win32screenshot (0.0.9)
win32screenshot (2.1.0)

C:\Users\Administrator>irb
irb(main):001:0> require 'win32/screenshot'
=> true
irb(main):002:0> Win32::Screenshot::Take.of(:foreground).write("image.png")
NameError: uninitialized constant Win32::Screenshot::Take
        from (irb):2
        from C:/Ruby22-x64/bin/irb:11:in `<main>'
irb(main):003:0> ^C

**Comment by jarmo** [comment] 2016-06-12 09:22
The problem is that you have rdp-win32screenshot (one fork of a win32screenshot older version) installed, which will be loaded instead of win32screenshot.

There's two possible solutions for this normal RubyGems behavior.

```ruby
irb(main):001:0> gem "win32screenshot"
=> true
irb(main):002:0> require "win32/screenshot"
=> true
irb(main):003:0> Win32::Screenshot::Take
=> Win32::Screenshot::Take
```

Or just uninstall rdp-win32screenshot.

Closing this issue.

**Closed by jarmo** 2016-06-12 09:22 UTC
